hmcts/ia-home-office-integration-api

- infrastructure/main.tf
Updating terraform files for a successful build on master branch
> changes for a good master pipeline

- infrastructure/main.tf
> Terraform update for master branch

- infrastructure/variables.tf
Infrastructure set up for master branch
> variables.trf modified

- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/demo/config/SwaggerPublisher.java
- src/smokeTest/java/uk/gov/hmcts/reform/demo/SmokeTest.java
- src/test/java/uk/gov/hmcts/reform/demo/controllers/RootControllerTest.java
Smoke test added to the pipeline
RIA-2794
> Smoke test added

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/SwaggerPublisher.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/GetWelcomeTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/Application.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackController.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/RootController.java
- src/smokeTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/SmokeTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/RootControllerTest.java
https://tools.hmcts.net/jira/browse/RIA-2792
https://tools.hmcts.net/jira/browse/RIA-2794
Basic CallbackController added to create the API structure
No domain entities added
> Home office controller introduced

- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/HomeOfficeConsumerTest.java
https://tools.hmcts.net/jira/browse/RIA-2795
Consumer contract added but without logic.
> PACT consumer contract added

- build.gradle
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/RequiredFieldMissingException.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCase.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/CaseDetails.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/State.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/callback/DispatchPriority.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/callback/PreSubmitCallbackResponse.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/callback/PreSubmitCallbackStage.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/CaseDetailsTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/StateTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/callback/DispatchPriorityTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/callback/PreSubmitCallbackResponseTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/callback/PreSubmitCallbackStageTest.java
Adding some domain classes and related tests
> Adding ia framework

- charts/ia-home-office-integration-api/Chart.yaml
- charts/ia-home-office-integration-api/values.yaml
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/variables.tf
Adding infrastructure and Helm
> Helm: Adding infra config

- Jenkinsfile_CNP
- build.gradle
- charts/ia-home-office-integration-api/values.aat.template.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/WelcomeFunctionTest.java
- src/functionalTest/resources/application-functional.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/GetWelcomeTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackControllerIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackController.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/WelcomeController.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/main/resources/config.properties
Adding bootstrap and config test to get value from vault
> Bootstrap and config test

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/WelcomeFunctionTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/WelcomeController.java
- src/main/resources/bootstrap.yaml
> Test vault working

- build.gradle
- charts/ia-home-office-integration-api/Chart.yaml
- charts/ia-home-office-integration-api/values.preview.template.yaml
- charts/ia-home-office-integration-api/values.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/WelcomeFunctionTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/WelcomeController.java
Testing we get the vault values back propertly
> Checking we get vault values correctly

- build.gradle
- docker-pactbroker-compose.yml
Publishing pact contract that was created
> pact publish

- Jenkinsfile_CNP
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/application-functional.yaml
Adding Security header functional test
> Add S2S functional test

- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/HomeOfficeConsumerTest.java
- target/pacts/hmcts-homeoffice_api.json
Update to PACT test to publish json file
> PACT publish file

- src/contractTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/HomeOfficeConsumerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/WelcomeFunctionTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/MapFieldAssertor.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/MapMerger.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/MapSerializer.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/MapValueExpander.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/MapValueExtractor.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/StringResourceLoader.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/verifiers/CaseDataVerifier.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/verifiers/Verifier.java
- src/functionalTest/resources/scenarios/RIA-3073-home-office-searchByParameters-response-for-appeal-submitted.json
- src/functionalTest/resources/scenarios/RIA-3073-sample-response-for-appeal-submitted.json
- src/functionalTest/resources/templates/aip-minimal-appeal-submitted.json
- src/functionalTest/resources/templates/minimal-appeal-started.json
- src/functionalTest/resources/templates/minimal-appeal-submitted.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
- target/pacts/hmcts-homeoffice_api.json
Scenario test framework added
As of now, testing a simple scenario where appeal is submitted and it returns the same asylum case data.
> RIA-3073 scenario test

- Jenkinsfile_CNP
- build.gradle
- config/owasp/suppressions.xml
- docker-compose.yml
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/EndpointSecurityTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/HomeOfficeCaseStatusClient.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/HomeOfficeResponseException.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/util/HomeOfficeApiUtil.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/HomeOfficeCaseStatusClientTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/util/HomeOfficeApiUtilTest.java
- src/test/resources/home-office-sample-response.json
REST call to Home office mock server.
We are not processing any elements but just connecting to the API.
> Call to mock server implemented

- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/HomeOfficeCaseStatusClientTest.java
Empty commit to resolve warning in AAT for master
> Empty commit add to just push to master

- src/contractTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/HomeOfficeConsumerTest.java
- src/functionalTest/resources/scenarios/RIA-3073-sample-response-for-appeal-submitted.json
RIA-3376: Contract for Error scenario
https://tools.hmcts.net/jira/browse/RIA-3376
```
[ ] Yes
[ x] No
```
> RIA-3376: Contract for Error scenario

- .travis.yml
- Dockerfile
- build.gradle
[RIA-3448](https://tools.hmcts.net/jira/browse/RIA-3448)
```
[x] Yes
[ ] No
```
> RIA-3448 upgrading to java11

- build.gradle
[RIA-3448](https://tools.hmcts.net/jira/browse/RIA-3448)
```
[ ] Yes
[x] No
```
> Java11 upgrade

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeSearchService.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
Connect with home office PRP1
https://tools.hmcts.net/jira/browse/RIA-3509
```
[ ] Yes
[ x] No
```
> Connect with home office PRP1

- Jenkinsfile_CNP
- charts/ia-home-office-integration-api/Chart.yaml
- charts/ia-home-office-integration-api/values.yaml
- src/functionalTest/resources/scenarios/RIA-3290-notification-for-appeal-submitted.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseNotificationHandlerTest.java
Home office PRP1 connect for Validation flow
Disabled notification flow and tests.
https://tools.hmcts.net/jira/browse/RIA-3532
```
[ ] Yes
[x ] No
```
> RIA-3509:Home office PRP1 connect for Validation flow

- Jenkinsfile_CNP
- charts/ia-home-office-integration-api/Chart.yaml
- charts/ia-home-office-integration-api/values.yaml
- src/functionalTest/resources/scenarios/RIA-3290-notification-for-appeal-submitted.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseNotificationHandlerTest.java
Reverts hmcts/ia-home-office-integration-api#105
> Revert "RIA-3509:Home office PRP1 connect for Validation flow"

- src/functionalTest/resources/scenarios/RIA-3378-expected-400-response-invalid-format.json
- src/functionalTest/resources/scenarios/RIA-3378-response-for-appeal-submitted-invalid-short-format.json
- src/functionalTest/resources/scenarios/RIA-3378-response-for-appeal-submitted-not-asylum-case.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-200-response-no-data-found.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted-non-uan-format.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ApplicationStatus.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/CodeWithDescription.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ConsumerReference.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/HomeOfficeCaseStatus.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/Person.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeSearchService.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/HomeOfficeSearchApi.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeSearchServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-3378
Added response logging for testing and more functional tests with PRP1 data
```
[ ] Yes
[X] No
```
> Ria 3378 ho auth

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
- src/test/resources/home-office-null-field-response.json
Handle null values in HO response
https://tools.hmcts.net/jira/browse/RIA-3510
```
[ ] Yes
[x ] No
```
> RIA-3510: Handle null values in HO response

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/RequestUserAccessTokenProvider.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamAuthorizor.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamUserDetailsProvider.java
Fixed new sonar issues raised on existing code
```
[ ] Yes
[X] No
```
> Fixed new sonar issues raised on existing code

- src/functionalTest/resources/scenarios/RIA-3378-response-for-appeal-submitted-not-asylum-case.json
Fixed test to be in sync with PRP1 response
```
[ ] Yes
[X] No
```
> Fixed test to be in sync with PRP1 response

- src/functionalTest/resources/scenarios/RIA-3271-sample-response-for-appeal-submitted.json
Disabling test until we get a confirmed expected response from PRP1
```
[ ] Yes
[X] No
```
> Disabling test until we get a confirmed expected response from PRP1

- Jenkinsfile_CNP
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RIA-3408
updated infra files with secret keys
```
[ ] Yes
[X] No
```
> RIA-3408: updated infra files with secret keys

- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/HomeOfficeStatusSearchIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/testutils/WithHomeOfficeStatusSearchStub.java
- src/integrationTest/resources/ho-api_get-by-search-params_200-valid_null_response.json
RIA-3533-3532:Add integration test for null field, handle HO endpoint change
https://tools.hmcts.net/jira/browse/RIA-3532
https://tools.hmcts.net/jira/browse/RIA-3533
```
[ ] Yes
[ x] No
```
> RIA-3533-3532:Add integration test for null field, handle HO endpoint change

- .github/workflows/swagger.yml
- .travis.yml
- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- README.md
- audit.json
- build.gradle
- docker-pactbroker-compose.yml
- security.sh
- src/functionalTest/resources/scenarios/RIA-3271-sample-response-for-appeal-submitted.json
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/SpringBootIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/testutils/TestConfiguration.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/SwaggerPublisher.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/BadRequestsTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeInstructService.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackController.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/WelcomeController.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeInstructServiceTest.java
RIA-3569:Nightly build, Publish Swagger, serenity report, README
This is a replacement for PR #127 as nightly-dev branch should not be used for PR
https://tools.hmcts.net/jira/browse/RIA-3569
```
[ ] Yes
[ x] No
```
> RIA-3569:Nightly build,Publish Swagger,serenity report,README

- Jenkinsfile_nightly
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-3332-response-for-mark-appeal-paid-event.json
- src/functionalTest/resources/scenarios/RIA-3332-response-for-pay-and-submit-event.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
RIA-3332: Add pay and submit appeal event
https://tools.hmcts.net/jira/browse/RIA-3332
```
[ ] Yes
[ x] No
```
> RIA-3332: Add pay and submit appeal event

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-fail.json
- src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-success.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ApplicationStatus.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/field/IdValue.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ApplicationStatusTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/field/IdValueTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
RIA-3390:Request Home Office data flow and negative scenario
https://tools.hmcts.net/jira/browse/RIA-3390
```
[ ] Yes
[x ] No
```
> RIA-3390:Request Home Office data flow and negative scenario

- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-error-code-1040.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-error-code-1070.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-error-code-2000.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-error-code-2010.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-invalid-format-1060.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-invalid-format-more-than-30char-reference.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-no-appellant-found-1010.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-no-appellant-found-1030.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-no-ho-reference-found-1020.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-no-main-applicant.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/FeignErrorDecoder.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/HomeOfficeResponseException.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/homeoffice/HomeOfficeAuthorizor.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
RIA-3545: Handle different error scenario
https://tools.hmcts.net/jira/browse/RIA-3545
```
[ ] Yes
[x ] No
```
> RIA-3545: Handle different error scenario

- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-no-appellant-found-1030.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-no-ho-reference-found-1020.json
RIA-3545-disable test for error against mock, fix functional test failing for RIA-3545
https://tools.hmcts.net/jira/browse/RIA-3545
```
[ ] Yes
[ x] No
```
> RIA-3545-disable test for error against mock

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeSearchService.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeSearchServiceTest.java
N/A
logging refactoring - adding caseId + removing whole response body log
```
[ ] Yes
[x] No
```
> logging refactoring - adding caseId + removing whole response body log

- charts/ia-home-office-integration-api/Chart.yaml
- charts/ia-home-office-integration-api/values.yaml
N/A
ingress host in app code
```
[ ] Yes
[x] No
```
> ingress host in app code

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeSearchService.java
https://tools.hmcts.net/jira/browse/RIA-3879
log correlation ID and cve fixes
```
[ ] Yes
[X] No
```
> RIA-3879: log correlation ID and cve fixes

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/WelcomeFunctionTest.java
[RIA-3705](https://tools.hmcts.net/jira/browse/RIA-3705)
```
[ ] Yes
[x] No
```
> RIA-3705 Serenity tests report fix for JUnit5 runner

- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/RIA-3306-notification-for-hearing-without-decision-fee-option.json
- src/functionalTest/resources/scenarios/RIA-3306-notification-for-hearing.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/Hearing.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/HearingInstructMessage.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/HearingType.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentre.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/WitnessDetails.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ListCaseNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/DateTimeExtractor.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentreTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AbstractNotificationsHandlerTestBase.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ListCaseNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestEvidenceBundleNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestEvidenceReviewNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/DateTimeExtractorTest.java
https://tools.hmcts.net/jira/browse/RIA-3306
Changes to send hearing notification to HO
```
[ ] Yes
[X] No
```
> Ria 3306 hearing notification

- src/functionalTest/resources/scenarios/RIA-3309-notification-for-hearing-edit-case-listing-decision.json
- src/functionalTest/resources/scenarios/RIA-3309-notification-for-hearing-edit-case-listing-finalbundling.json
- src/functionalTest/resources/scenarios/RIA-3309-notification-for-hearing-edit-case-listing-prehearing-co.json
- src/functionalTest/resources/scenarios/RIA-3309-notification-for-hearing-edit-case-listing-prehearing.json
- src/functionalTest/resources/scenarios/RIA-3309-notification-for-hearing-edit-case-listing-prepareforhearing.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ListCaseNotificationHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ListCaseNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-3309
RIA-3309 ho hearing
```
[ ] Yes
[X] No
```
> Ria 3309 ho hearing

- src/functionalTest/resources/scenarios/RIA-3316-notification-for-adjourn-hearing-without-date-decision.json
- src/functionalTest/resources/scenarios/RIA-3316-notification-for-adjourn-hearing-without-date-finalbundling.json
- src/functionalTest/resources/scenarios/RIA-3316-notification-for-adjourn-hearing-without-date-prehearing-co.json
- src/functionalTest/resources/scenarios/RIA-3316-notification-for-adjourn-hearing-without-date-prehearing.json
- src/functionalTest/resources/scenarios/RIA-3316-notification-for-adjourn-hearing-without-date-prepareforhearing.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AdjournHearingWithoutDateNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/EditCaseListingNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestEvidenceBundleNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestEvidenceReviewNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/ListingNotificationHelper.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/NotificationsHelper.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AbstractNotificationsHandlerTestBase.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AdjournHearingWithoutDateNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/EditCaseListingNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ListingNotificationHelperTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/NotificationsHelperTest.java
https://tools.hmcts.net/jira/browse/RIA-3316
RIA-3316 adjourned with no hearing date
```
[ ] Yes
[X] No
```
> Ria 3316 no hearing date

- src/functionalTest/resources/scenarios/RIA-3601-notification-for-request-evidence-400-bad-request-response.json
- src/functionalTest/resources/scenarios/RIA-3601-notification-for-request-evidence-500-api-response.json
- src/functionalTest/resources/scenarios/RIA-3601-notification-for-request-evidence-500-service-unavailable-response.json
- src/functionalTest/resources/scenarios/RIA-3601-notification-for-request-evidence-503-response.json
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/HomeOfficeInstructIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/testutils/IntegrationConstants.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/testutils/WithHomeOfficeAuthStub.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/testutils/WithHomeOfficeInstructStub.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/CustomFeignRetryer.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeInstructService.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/FeignErrorDecoder.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/HomeOfficeTokenApi.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/RetriesExceededException.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/homeoffice/HomeOfficeAuthorizor.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/FeignErrorDecoderTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/homeoffice/HomeOfficeAuthorizorTest.java
https://tools.hmcts.net/jira/browse/RIA-3601
Feign Retryer added. Removed RestTemplate, Added functional tests and integration tests.
```
[ ] Yes
[X] No
```
> RIA-3601: Feign Retryer added. Removed RestTemplate, Added functional tests and integration tests.

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-3314-notification-for-appeal-decided-admin-officer.json
- src/functionalTest/resources/scenarios/RIA-3314-notification-for-appeal-decided-case-officer.json
- src/functionalTest/resources/scenarios/RIA-3314-notification-for-appeal-decided-judge.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AppealDecidedInstructMessage.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AppealDecision.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/CourtOutcome.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AppealDecidedNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/AppealDecidedNote.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AppealDecisionTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/CourtOutcomeTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/MessageTypeTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AppealDecidedNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-3314
Home Office appeal decided notification
```
[ ] Yes
[X] No
```
> Ria 3314 decided notification

- src/functionalTest/resources/scenarios/RIA-3305-notification-for-async-stitching-complete-co.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/Hearing.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/HearingBundleReadyNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/ListingNotificationHelper.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AbstractNotificationsHandlerTestBase.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/HearingBundleReadyNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ListingNotificationHelperTest.java
https://tools.hmcts.net/jira/browse/RIA-3305
RIA-3305  hearing  bundle ready
```
[ ] Yes
[X] No
```
> Ria 3305 hearing bundle ready

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-3313-notification-for-ftpa-appellant-decided.json
- src/functionalTest/resources/scenarios/RIA-3313-notification-for-ftpa-appellant-ftpa-decided.json
- src/functionalTest/resources/scenarios/RIA-3313-notification-for-ftpa-appellant-ftpa-submitted.json
- src/functionalTest/resources/scenarios/RIA-3313-notification-for-ftpa-respondent-decided-homeoffice-generic-submit.json
- src/functionalTest/resources/scenarios/RIA-3313-notification-for-ftpa-respondent-decided-homeoffice-pou-submit.json
- src/functionalTest/resources/scenarios/RIA-3313-notification-for-ftpa-respondent-ftpa-submitted-homeoffice-generic-submit.json
- src/functionalTest/resources/scenarios/RIA-3313-notification-for-ftpa-respondent-ftpaDecided-homeoffice-pou-submit.json
- src/functionalTest/resources/scenarios/RIA-3313-notification-for-ftpa-respondent-ftpaSubmitted-homeoffice-pou-submit.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/CourtType.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/PermissionToAppealInstructMessage.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/FtpaAppellantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/FtpaRespondentNotificationHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/CourtTypeTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/FtpaAppellantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/FtpaRespondentNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-3313
CHanges to send HO notification on FTPA submission
```
[ ] Yes
[X] No
```
> Ria 3313 ftpa submitted notification

- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-3302-notification-for-end-appeal-on-state-appeal-submitted-co.json
- src/functionalTest/resources/scenarios/RIA-3302-notification-for-end-appeal-on-state-case-building-admin.json
- src/functionalTest/resources/scenarios/RIA-3302-notification-for-end-appeal-on-state-case-building-judge.json
- src/functionalTest/resources/scenarios/RIA-3302-notification-for-end-appeal-on-state-case-under-review-admin.json
- src/functionalTest/resources/scenarios/RIA-3302-notification-for-end-appeal-on-state-final-bundling-judge.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/EndAppealInstructMessage.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/EndAppealOutcome.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/EndAppealNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/util/HomeOfficeDateFormatter.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/EndAppealNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/util/HomeOfficeDateFormatterTest.java
https://tools.hmcts.net/jira/browse/RIA-3302
RIA-3302 ho end appeal
```
[ ] Yes
[X] No
```
> Ria 3302 ho end appeal

- src/functionalTest/resources/scenarios/RIA-3691-notification-for-amend-bundle-for-send-direction.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AmendBundleNotificationHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AmendBundleNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-3691
RIA-3691 amend bundle
```
[ ] Yes
[X] No
```
> Ria 3691 amend bundle

- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/RIA-3692-notification-for-amend-response-for-respondent -review.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AmendResponseNotificationHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AmendResponseNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-3692
RIA-3692 amend response
```
[ ] Yes
[X] No
```
> Ria 3692 amend response

- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/RIA-3693-notification-for-change-direction-due-date-co.json
- src/functionalTest/resources/scenarios/RIA-3693-notification-for-change-direction-due-date-judge.json
- src/functionalTest/resources/scenarios/RIA-3693-notification-for-change-direction-due-date-respondent-review-co.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ChangeDirectionDueDateNotificationHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ChangeDirectionDueDateNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-3693
RIA-3693 direction due date
```
[ ] Yes
[X] No
```
> Ria 3693 direction due date

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeInstructService.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeInstructServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-3970
Refactored to log correlation id and fixed test
```
[ ] Yes
[X] No
```
> RIA-3970: Refactored to log correlation id and fixed test

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-3749
optimised retry and http timeout values for Feign client
```
[ ] Yes
[X] No
```
> RIA-3749: optimised retry and http timeout values for Feign client

- src/functionalTest/resources/scenarios/RIA-3271-sample-response-for-appeal-submitted.json
- src/functionalTest/resources/scenarios/RIA-3332-response-for-mark-appeal-paid-event.json
- src/functionalTest/resources/scenarios/RIA-3332-response-for-pay-and-submit-event.json
- src/functionalTest/resources/scenarios/RIA-3378-expected-400-response-invalid-format.json
- src/functionalTest/resources/scenarios/RIA-3378-response-for-appeal-submitted-invalid-short-format.json
- src/functionalTest/resources/scenarios/RIA-3378-response-for-appeal-submitted-not-asylum-case.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-200-response-no-data-found-cid-ref.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-200-response-no-data-found-uan-ref.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted-non-uan-format.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted.json
- src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-fail.json
- src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-success.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-invalid-format-more-than-30char-reference.json
https://tools.hmcts.net/jira/browse/RIA-3749
Temporarily disabled validation functional tests until PRP1 is available and enable retry testing while it is unavailable
```
[ ] Yes
[X] No
```
> RIA-3749: Temporarily disabled validation functional tests until PRP1 is available and enable retry testing while it is unavailable

- charts/ia-home-office-integration-api/Chart.yaml
[RIA-3710](https://tools.hmcts.net/jira/browse/RIA-3710)
```
[ ] Yes
[x] No
```
> RIA-3710 Migrate to Helm charts v2

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/FeatureToggleConfiguration.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/LaunchDarklyFunctionalTestClient.java
- src/functionalTest/resources/application-functional.yaml
- src/main/resources/application.yaml
N/A
refactoring Launch Darkly client
```
[ ] Yes
[x] No
```
> refactoring Launch Darkly client

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/FeatureToggleConfiguration.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/LaunchDarklyFunctionalTestClient.java
[RIA-4054](https://tools.hmcts.net/jira/browse/RIA-4054)
```
[ ] Yes
[x] No
```
> RIA-3710 reverting back from launchdarkly upgrade

- src/functionalTest/resources/scenarios/RIA-3271-sample-response-for-appeal-submitted.json
- src/functionalTest/resources/scenarios/RIA-3332-response-for-mark-appeal-paid-event.json
- src/functionalTest/resources/scenarios/RIA-3332-response-for-pay-and-submit-event.json
- src/functionalTest/resources/scenarios/RIA-3378-expected-400-response-invalid-format.json
- src/functionalTest/resources/scenarios/RIA-3378-response-for-appeal-submitted-invalid-short-format.json
- src/functionalTest/resources/scenarios/RIA-3378-response-for-appeal-submitted-not-asylum-case.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-200-response-no-data-found-cid-ref.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-200-response-no-data-found-uan-ref.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted-non-uan-format.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted.json
- src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-fail.json
- src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-success.json
- src/functionalTest/resources/scenarios/RIA-3545-valid-200-response-invalid-format-more-than-30char-reference.json
https://tools.hmcts.net/jira/browse/RIA-3749
Reverted Temporarily disabled validation functional tests.
```
[ ] Yes
[X] No
```
> RIA-3749: Reverted Temporarily disabled validation functional tests.

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/FeatureToggleConfiguration.java
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/util/LaunchDarklyFunctionalTestClient.java
- src/functionalTest/resources/application-functional.yaml
[RIA-4054](https://tools.hmcts.net/jira/browse/RIA-4054)
```
[ ] Yes
[x] No
```
> RIA-4054 Upgrade launchdarkly version from 4.14.1 to 5.2.2 (#202)

- Jenkinsfile_CNP
- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/idam/IdamApiConsumerApplication.java
- src/contractTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/idam/IdamApiConsumerTest.java
TA-550
Added PACT consumer contract tests
```
[ ] Yes
[X] No
```
> TA-550 Consumer contract tests

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeInstructService.java
Removed request and response logging
```
[ ] Yes
[X] No
```
> Removed request and response logging

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentre.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/RIA-3720
see ticket
```
[ ] Yes
[ X] No
```
> RIA-3720 AO lists the case (remote hearing)

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/ListingNotificationHelper.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/ListingNotificationHelperTest.java
[RIA-3722](https://tools.hmcts.net/jira/browse/RIA-3722)
See Jira
```
[ ] Yes
[x] No
```
> RIA-3722 edit listing

- build.gradle
- charts/ia-home-office-integration-api/Chart.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/EndpointSecurityTest.java
- src/functionalTest/resources/scenarios/RIA-3332-response-for-mark-appeal-paid-event.json
- src/functionalTest/resources/scenarios/RIA-3332-response-for-pay-and-submit-event.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted-non-uan-format.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted.json
- src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-success.json
- src/functionalTest/resources/scenarios/RIA-3980-home-office-response-matchin-applicant-dob.json
- src/functionalTest/resources/scenarios/RIA-3980-home-office-response-matching-applicant-name.json
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/HomeOfficeStatusSearchIntegrationTest.java
- src/integrationTest/resources/ho-api_get-by-search-params_200-extra-fields_response.json
- src/integrationTest/resources/ho-api_get-by-search-params_200-valid_null_response.json
- src/integrationTest/resources/ho-api_get-by-search-params_200-valid_response.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
- src/test/resources/home-office-sample-response.json
[RIA-3980](https://tools.hmcts.net/jira/browse/RIA-3980)
Match the HomeOffice Applicant details against name or dob
```
[ ] Yes
[x] No
```
> RIA-3980 Match applicant by either name or dob

- .gitignore
- src/functionalTest/resources/scenarios/RIA-3271-sample-response-for-appeal-submitted.json
- src/functionalTest/resources/scenarios/RIA-3332-response-for-mark-appeal-paid-event.json
- src/functionalTest/resources/scenarios/RIA-3332-response-for-pay-and-submit-event.json
- src/functionalTest/resources/scenarios/RIA-3378-valid-response-for-appeal-submitted.json
- src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-success.json
> RIA-3980 Updated the functional tests with DOB to assert SUCCESS

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
> RIA-3980 Updated HomeOffice decision date format

- build.gradle
[RIA-4278](https://tools.hmcts.net/jira/browse/RIA-4278)
fix CVE and upgrade charts
```
[ ] Yes
[x] No
```
> RIA-4278 fix CVE and upgrade charts

- charts/ia-home-office-integration-api/Chart.yaml
- charts/ia-home-office-integration-api/values.aat.template.yaml
N/A
change staging pod to connect to mock-api
```
[ ] Yes
[x] No
```
> change staging pod to connect to mock-api

- .github/workflows/swagger.yml
- audit.json
N/A
fix Security scan
```
[ ] Yes
[x] No
```
> fix Security scan

- build.gradle
- src/functionalTest/resources/scenarios/RIA-4557-appeal-submitted-with-multiple-matching-appellants.json
- src/functionalTest/resources/scenarios/RIA-4557-display-selected-appellant-details.json
- src/functionalTest/resources/scenarios/RIA-4557-display-selected-appellant-with-pp-number.json
- src/functionalTest/resources/scenarios/RIA-4557-do-not-display-appellant-details-for-no-match.json
- src/functionalTest/resources/scenarios/RIA-4557-show-no-match-for-no-appellants-found.json
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/HomeOfficeStatusSearchIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/HomeOfficeDataErrorsHelper.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCase.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/DynamicList.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/Value.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataPreparer.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/SubmitAppealApplicantSearchHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/FeatureToggler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeSearchService.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/FeignErrorDecoder.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/LaunchDarklyFeatureToggler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/FeatureToggleConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/UserDetailsProviderConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackController.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataPreparerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/SubmitAppealApplicantSearchHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/client/LaunchDarklyFeatureTogglerTest.java
- src/test/resources/home-office-multiple-applicants-response.json
[RIA-4557](https://tools.hmcts.net/jira/browse/RIA-4557)
Request HomeOffice data of the matching appellant details
```
[ ] Yes
[x] No
```
> RIA-4557 Request Home Office data of the matching appellant details

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
N/A
fix NFE in search validation handler
```
[ ] Yes
[x] No
```
> fix NFE in search validation handler

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/HomeOfficeDataMatchHelper.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataHandler.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataPreparer.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/SubmitAppealApplicantSearchHandler.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/AsylumCaseStatusSearchHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataPreparerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/SubmitAppealApplicantSearchHandlerTest.java
[RIA-4556](https://tools.hmcts.net/jira/browse/RIA-4556)
Added HomeOffice atleast one matching criteria
```
[ ] Yes
[x] No
```
> RIA-4556 HomeOffice UAN atleast one matching criteria

- charts/ia-home-office-integration-api/Chart.yaml
N/A
Charts upgrade 3.6.0
```
[ ] Yes
[x] No
```
> Charts upgrade 3.6.0

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/HomeOfficeDataErrorsHelper.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataPreparer.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/handlers/presubmit/RequestHomeOfficeDataPreparerTest.java
[RIA-4773](https://tools.hmcts.net/jira/browse/RIA-4773)
Display No match in case Home Office Api error
```
[ ] Yes
[x] No
```
> RIA-4773 Display No match for Home Office API error

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentre.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/RIA-4861
Added missing hearing centre Belfast
```
[ ] Yes
[X] No
```
> RIA-4861: Added missing hearing centre Belfast

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/Direction.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/DirectionTest.java
https://tools.hmcts.net/jira/browse/RIA-4540
Updated Direction entity to reflect the additional fields
```
[ ] Yes
[X] No
```
> RIA-4540: Updated Direction entity to reflect the additional fields

- charts/ia-home-office-integration-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```
> RIA-5503: Upgrade base helm charts to latest

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AppealType.java
- [RIA-5587](https://tools.hmcts.net/jira/browse/RIA-5587)
- [RIA-5895](https://tools.hmcts.net/jira/browse/RIA-5895)
- [RIA-5586](https://tools.hmcts.net/jira/browse/RIA-5586)
- [RIA-6163](https://tools.hmcts.net/jira/browse/RIA-6163)
- Added EU ("EU Settlement Scheme" to AppealType enum)
```
[ ] Yes
[x] No
```
> RIA-5587 Add EU appealType

- src/main/resources/application.yaml
SNI-2650
Updates to include mark appeal as paid for case officer
Updates to include mark appeal as paid for case officer
```
[ ] Yes
[ ] No
```
> Updates to include mark appeal as paid for case officer

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- build.gradle
- charts/ia-home-office-integration-api/Chart.yaml
- config/owasp/suppressions.xml
To upgrade java chart version
To upgrade java chart version
```
[ ] Yes
[ X] No
```
> To upgrade java chart version

- charts/ia-home-office-integration-api/Chart.yaml
To revise chart version
To revise chart version
```
[ ] Yes
[X ] No
```
> To revise chart version

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/State.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/StateTest.java
https://tools.hmcts.net/jira/browse/RIA-6694
Allow admin to access the submitAppeal event. 
```
[ ] Yes
[x ] No
```
> Ria 6694 admin submit appeal

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6733
* Give TCW access to the event 'markAppealPaid'
```
[ ] Yes
[x] No
```
> RIA-6733: Make 'Mark appeal as paid' event available for internal cases

- charts/ia-home-office-integration-api/Chart.yaml
- config/owasp/suppressions.xml
Updates to suppress CVEs in naba branch
Updates to suppress CVEs in naba branch
```
[ ] Yes
[X ] No
```
> Updates to suppress CVEs in naba branch

- config/owasp/suppressions.xml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7057
-Add the permission of "applyForFTPAAppellant" event for citizen (fix the bug when citizen trigger "applyForFTPAAppellant" event)
-Temporary suppress the CVE problem (CVE-2023-20863) and update the expiry date of CVE list
```
[ ] Yes
[X] No
```
> RIA-7057-enable-FTPA-PA-and-revocation-protection-status

- infrastructure/variables.tf
RIA-7171
Small change in variables.tf
```
[ ] Yes
[x] No
```
> RIA-7171 Update to variables.tf

- infrastructure/output.tf
- infrastructure/variables.tf
RIA-7171
Updates for logging
```
[ ] Yes
[x] No
```
> RIA-7171 Updates for logging (hopefully)

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/HomeOfficeInstructService.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/homeoffice/HomeOfficeAuthorizor.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/homeoffice/HomeOfficeAuthorizorTest.java
RIA-7171
Improvements to logging do detect potential authentication issues.
```
[ ] Yes
[x] No
```
> RIA-7171 Updates for logging

- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/HomeOfficeInstructIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/HomeOfficeStatusSearchIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/SpringBootIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/testutils/StaticPortWiremockFactory.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/SwaggerPublisher.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackController.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/WelcomeController.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/homeoffice/HomeOfficeAuthorizor.java
RIA-7171
Revert changes done to build.gradle and related artifacts in an attempt to fix the ongoing production issues.
```
[ ] Yes
[x] No
```
> Revert CVE upgrades due to lib compatibility issue

- config/owasp/suppressions.xml
> Empty line commit

- config/owasp/suppressions.xml
> Rebuild naba branch & suppress vulnerabilities

- config/owasp/suppressions.xml
> RIA-7585 Empty line commit

- build.gradle
- config/owasp/suppressions.xml
RIA-7251
Restructuring the build.gradle file to remove duplication and deprecated constructs to facilitate new attempts at fixing CVEs.
```
[ ] Yes
[x] No
```
> RIA-7251 Restructuring build.gradle file

- config/owasp/suppressions.xml
> RIA-7363 Empty commit

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-5679
Updating suppressions
```
[ ] Yes
[X] No
```
> RIA-5679 updating suppressions

- .github/renovate.json
Added renovate.json
```
[ ] Yes
[ z] No
```
> RIA-111 renovate json patch

- config/owasp/suppressions.xml
> RIA-7777 updating suppressions for pipeline

- src/functionalTest/resources/scenarios/RIA-7879-notification-for-new-hearing-centre-harmondsworth.json
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentre.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/RIA-7879
- Added the new hearing venue to location list
- Added unit test and functional test
```
[ ] Yes
[X] No
```
> RIA-7879 map epims ids to ccd hearing locations

- config/owasp/suppressions.xml
Updating for pipeline
```
[ ] Yes
[ x ] No
```
> RIA-7814 update suppressions.xml

- build.gradle
- config/owasp/suppressions.xml
Rebuilding image
```
[ ] Yes
[ x ] No
```
> RIA-7454 update suppressions.xml

- charts/ia-home-office-integration-api/Chart.yaml
upgrade chart version
```
[ ] Yes
[ x ] No
```
> RIA-8888 upgrade chart version

- charts/ia-home-office-integration-api/Chart.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/field/WitnessDetailsTest.java
https://tools.hmcts.net/jira/browse/RIA-7195
- Added the unit test for witnessDetails class
- Updated the chart java version from 4.0.13 to 5.0.0 because PR failed in pipeline
```
[ ] Yes
[X] No
```
> RIA-7195 remove listing reference number from notification template v3

- build.gradle
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/WitnessDetails.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/field/WitnessDetailsTest.java
[RIA-7922](https://tools.hmcts.net/jira/browse/RIA-7922)
- Updated WitnessDetails class
> RIA-7792 Add field to WitnessDetails

- build.gradle
- config/owasp/suppressions.xml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/UuidIdentityProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7734
Tiny change for NABA rebuild
```
[ ] Yes
[ ] No
```
> RIA-7734 fix_image

- Jenkinsfile_nightly
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
https://tools.hmcts.net/jira/browse/DIAC-69
```
[ ] Yes
[ ] No
```
> DIAC-69 getting all functionals running

- build.gradle
- charts/ia-home-office-integration-api/Chart.yaml
https://github.com/hmcts/ia-bail-case-api/pull/406
Updating Chart version to 5.0.0
```
[ ] Yes
[ ] No
```
> RIA-1150 updating chart version to 5.0.0

- .github/renovate.json
https://tools.hmcts.net/jira/browse/DIAC-2
Updating renovate JSON
```
[ ] Yes
[x] No
```
> DIAC-002-updating-renovate.json

- src/main/resources/application.yaml
[RIA-7881](https://tools.hmcts.net/jira/browse/RIA-7881)
- Added `listCase`, `editCaseListing` to events allowed for caseworker-ia-system
```
[ ] Yes
[x] No
```
> RIA-7881 Allow listCase for system user

- .github/workflows/pr-title-validation.yml
- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DIAC-173
```
[ ] Yes
[ ] No
```
> DIAC-173 updating dependency and pr validation

- config/owasp/suppressions.xml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ClarifyingQuestionTest.java
Restart the pipelines
```
[ ] Yes
[ ] No
```
> RIA-2023 rebuild_pipelines

- Dockerfile
- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/DIAC-101
```
[ ] Yes
[ ] No
```
> DIAC-101 turning fortify on for nightly build

- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java
https://tools.hmcts.net/jira/browse/RIA-7833
- To rebuild pipeline
> RIA-7833 Commit to rebuild pipeline

- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/Parties.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/PartiesTest.java
https://tools.hmcts.net/jira/browse/SNI-5296
Fixing parties class
```
[ ] Yes
[x] No
```
> DIAC-211 adding new party

- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/DecideFtpaApplicationOutcomeTypeTest.java
> RIA-8104 Fix sonnar issue

- config/owasp/suppressions.xml
Rebuild image
```
[ ] Yes
[ x ] No
```
> RIA-8157 update suppressions.xml

- config/owasp/suppressions.xml
update suppressions.xml
```
[ ] Yes
[ x ] No
```
> RIA-8257 update suppressions.xml

- config/owasp/suppressions.xml
Committing to trigger build image
> RIA-TASK - Committing to trigger build image

- config/owasp/suppressions.xml
- src/functionalTest/resources/scenarios/RIA-7879-notification-for-new-hearing-centre-harmondsworth.json
> RIA-0000 Fix failing functional test

- src/functionalTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/CcdScenarioRunnerTest.java
https://tools.hmcts.net/jira/browse/RIA-8758
- CcdScenarioRunnerTest changes rebased from master
- Draft to run functional tests on pipeline
```
[ ] Yes
[X] No
```
> RIA-8758 DLRM rebase from master for CcdScenarioRunnerTest

- config/owasp/suppressions.xml
retrigger NABA image build
```
[ ] Yes
[ x ] No
```
> RIA-8888 retrigger NABA image build

- config/owasp/suppressions.xml
Rebuild image
```
[ ] Yes
[ x ] No
```
> RIA-8888 updated suppressions.xml

- config/owasp/suppressions.xml
[DIAC-370](https://tools.hmcts.net/jira/browse/DIAC-370)
[DIAC-371](https://tools.hmcts.net/jira/browse/DIAC-371)
Remove unnecessary suppressions CVE-2016-1000027 and CVE-2022-45688.
```
[ ] Yes
[ ] No
```
> DIAC-366 CVEs

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-8609
```
[ ] Yes
[ x] No
```
> RIA-8609 - Cherry picked 5f79181b 16/04/2024

- Jenkinsfile_nightly
- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/Config.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/BadRequestsTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/Parties.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/IdamService.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/CacheConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/UserDetailsProviderConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamAuthoritiesConverter.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamUserDetailsProvider.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/PartiesTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/IdamServiceTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamAuthoritiesConverterTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamUserDetailsProviderTest.java
> RIA-TASK - Resolve Merge Conflict

- Jenkinsfile_nightly
- build.gradle
- infrastructure/variables.tf
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/HomeOfficeInstructIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/component/HomeOfficeStatusSearchIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/Config.java
- src/integrationTest/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/BadRequestsTest.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/DirectionTag.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/Parties.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentre.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/State.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/IdamService.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/CacheConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/config/UserDetailsProviderConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamAuthoritiesConverter.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamUserDetailsProvider.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/AppealDecisionTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ClarifyingQuestionTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/DirectionTagTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/PartiesTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentreTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/StateTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/IdamServiceTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/service/UuidIdentityProviderTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamAuthoritiesConverterTest.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/infrastructure/security/idam/IdamUserDetailsProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-8860
RIA-8860 Merge with master
> RIA-8860 Merge with master

- charts/ia-home-office-integration-api/Chart.yaml
https://tools.hmcts.net/jira/browse/DIAC-401
> DIAC-401 bump chart version

- charts/ia-home-office-integration-api/Chart.yaml
Bump charts version
Some of the template versions/names were straightened out in the 5.2.1 release. We're hoping this will help fix https://tools.hmcts.net/jira/browse/DIAC-401
> DIAC-401 Update Chart Version

- build.gradle
[DIAC-600](https://tools.hmcts.net/jira/browse/DIAC-600)
```
[ ] Yes
[ ] No
```
> DIAC-600 removing deprecated reform jcenter

- charts/ia-home-office-integration-api/Chart.yaml
- config/owasp/suppressions.xml
> DIAC-000 - dependency-suppressions

- config/owasp/suppressions.xml
See [DIAC-1278](https://tools.hmcts.net/jira/browse/DIAC-1278)
```
[ ] Yes
[ ] No
```
> DIAC-123 suppression

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentre.java
- src/test/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/ccd/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/DIAC-1105
Add Virtual hearing location
```
[ ] Yes
[x] No
```
> DIAC-1105 Add Virtual Hearing location
